spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${pani.nacos.host:127.0.0.1}:8848
    gateway:
      routes:
        - id: aurora-oj-user-service
          uri: lb://aurora-oj-user-service
          predicates:
            - Path=/api/user/**
        - id: aurora-oj-question-service
          uri: lb://aurora-oj-question-service
          predicates:
            - Path=/api/question/**
        - id: aurora-oj-judge-service
          uri: lb://aurora-oj-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: aurora-oj-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
pani:
  nacos:
    host: 127.0.0.1
